AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  itable
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: id
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-s3b
      AccessControl: PublicRead
  InsertDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: insert/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /insert
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/'
                    - Ref: DynamoDBTable
  ReadDynamoDBEvent:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: read_dynamodb_event/
            Handler: app.lambda_handler
            Runtime: python3.9
            Events:
              DynamoDBEvent:
                  Type: DynamoDB # More info about DynamoDB Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb
                  Properties:
                      Stream:
                          !GetAtt DynamoDBTable.StreamArn
                      StartingPosition: TRIM_HORIZON
                      BatchSize: 10
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 's3:PutObject'
                      - 's3:PutObjectAcl'
                    Resource:
                      'Fn::Join':
                        - ''
                        - - !GetAtt S3Bucket.Arn
                          - '/*'
  ReadS3Event:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: read_s3_event/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events:
              - 's3:ObjectCreated:*'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/'
                    - Ref: DynamoDBTable

Outputs:
  ApiGatewayApi:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.us-eats-2.amazonaws.com/dev/"